ignores:
  - depcheck
  - declapract
  - declapract-typescript-ehmpathy
  - '@commitlint/config-conventional'
  - test-fns
  - '@ehmpathy/error-fns'
  - husky
  - if-env
  - "@src/*"
  - "@src/.*"
  - rhachet
  - "@tsconfig/node20"
  - "@tsconfig/strictest"
  - "@biomejs/biome"
  - esbuild-register
  - "@swc/core"
  - "@swc/jest"
  - tsx
  - tsc-alias
  - yalc
